- name: 'Provision Image'
  hosts: default
  become: true
  vars:
    helm_version: v3.4.0
    helmfile_version: v0.134.0
    k3s_version: v1.19.3+k3s2
    radar_kubernetes_version: dev

  tasks:
    - name: Install packages
      package:
        name: 'git'
        state: present

    - name: Create temporary helm directory
      file:
        path: /tmp/helm
        state: directory
        mode: '0755'

    - name: Download Helm archive
      get_url:
        url: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
        dest: /tmp/helm/helm.tar.gz

    - name: Extract Helm archive
      unarchive:
        src: /tmp/helm/helm.tar.gz
        dest: /tmp/helm
        remote_src: true

    - name: Move Helm binary to bin directory
      copy:
        src: /tmp/helm/linux-amd64/helm
        dest: /usr/local/bin/helm
        mode: '0755'
        remote_src: true

    - name: Remove temporary helm directory
      file:
        path: /tmp/helm
        state: absent

    - name: Install helm-diff
      command: helm plugin install https://github.com/databus23/helm-diff

    - name: Instal Helmfile
      get_url:
        url: https://github.com/roboll/helmfile/releases/download/{{ helmfile_version }}/helmfile_linux_amd64
        dest: /usr/local/bin/helmfile
        mode: '0755'

    - name: Get K3S installation script
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
      get_url:
        url: https://get.k3s.io/
        dest: /opt/k3s-install.sh
        mode: '0755'

    - name: Create K3S config directory
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: '0755'

    - name: Copy K3S configuration
      copy:
        src: files/k3s-config.yaml
        dest: /etc/rancher/k3s/config.yaml

    - name: Install K3S
      command: /opt/k3s-install.sh

    - name: Get RADAR-Kubernetes
      git:
        repo: 'https://github.com/RADAR-base/RADAR-Kubernetes.git'
        dest: /opt/RADAR-Kubernetes
        version: {{ radar_kubernetes_version }}

    - name: Create environments.yaml
      copy:
        src: templates/environments.yaml
        dest: /opt/RADAR-Kubernetes/environments.yaml

    - name: Create production.yaml
      copy:
        src: templates/production.yaml
        dest: /opt/RADAR-Kubernetes/production.yaml

    - name: Create production.yaml.gotmpl
      copy:
        src: templates/production.yaml.gotmpl
        dest: /opt/RADAR-Kubernetes/production.yaml.gotmpl

